# Generated by Django 3.0 on 2025-04-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ambulance_positioning_prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fid', models.CharField(max_length=3000)),
                ('Temp', models.CharField(max_length=3000)),
                ('Wind', models.CharField(max_length=3000)),
                ('Date_Time', models.CharField(max_length=3000)),
                ('Age_band_of_driver', models.CharField(max_length=3000)),
                ('Sex_of_driver', models.CharField(max_length=3000)),
                ('Vehicle_driver_relation', models.CharField(max_length=3000)),
                ('Driving_experience', models.CharField(max_length=3000)),
                ('Type_of_vehicle', models.CharField(max_length=3000)),
                ('Area_accident_occured', models.CharField(max_length=3000)),
                ('Types_of_Junction', models.CharField(max_length=3000)),
                ('Type_of_collision', models.CharField(max_length=3000)),
                ('Number_of_vehicles_involved', models.CharField(max_length=3000)),
                ('Number_of_casualties', models.CharField(max_length=3000)),
                ('Vehicle_movement', models.CharField(max_length=3000)),
                ('Cause_of_accident', models.CharField(max_length=3000)),
                ('Accident_severity', models.CharField(max_length=3000)),
                ('Ambulace_Allocated', models.CharField(max_length=3000)),
                ('Ambulace_Pickedup', models.CharField(max_length=3000)),
                ('Latitude', models.CharField(max_length=3000)),
                ('Longitude', models.CharField(max_length=3000)),
                ('Prediction', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='ClientRegister_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=10)),
                ('phoneno', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='detection_accuracy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='detection_ratio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
    ]
